version: "3"

services:
      
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cexplorer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cexplorer"]
      interval: 10s
      timeout: 5s
      retries: 5

  lyra:
    image: lyra
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./daemon.toml:/etc/lyra/daemon.toml
      - ./reduce.js:/reduce.js
    restart: on-failure