version: "3"

services:

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  lyra:
    image: lyra:v0.1.0
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./daemon.toml:/etc/lyra/daemon.toml
    restart: on-failure